cache:
  paths:
    - venv/

before_script:
  - python3 -V
  - python3 -m venv venv
  - source venv/bin/activate
  - python -m pip install --upgrade pip
  - python -m pip install . .[test]

run_tests:
  script:
    - pytest tests
  stage: test
