name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
      - '*'

pr:
  autoCancel: true
  branches:
    include:
      - '*'

schedules:
  - cron: 0 0 * * *
    displayName: Daily build
    branches:
      include:
        - main
    always: true

pool:
  vmImage: $(vmImage)

strategy:
  matrix:
    linux37:
      versionSpec: '3.7'
      vmImage: ubuntu-latest
    linux38:
      versionSpec: '3.8'
      vmImage: ubuntu-latest
    linux39:
      versionSpec: '3.9'
      vmImage: ubuntu-latest
    linux310:
      versionSpec: '3.10'
      vmImage: ubuntu-latest
    windows37:
      versionSpec: '3.7'
      vmImage: windows-latest
    windows38:
      versionSpec: '3.8'
      vmImage: windows-latest
    windows39:
      versionSpec: '3.9'
      vmImage: windows-latest
    windows310:
      versionSpec: '3.10'
      vmImage: windows-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(versionSpec)
  displayName: python$(versionSpec)

- script: |
    python -m pip install --upgrade pip
    python -m pip install . .[test]
  displayName: pip

- script: pytest
  displayName: pytest tests
